sudo: required

services:
  - docker
  
language: c
  
script:
  - docker pull debian
  - docker run -v $(pwd):/mnt debian /bin/sh -c "cd /mnt; export LANG=en_US.UTF-8; export LC_ALL=en_US.UTF-8; localectl en_US.UTF-8; locale-gen; apt-get update; apt-get install --assume-yes binutils build-essential git subversion cvs unzip whois ncurses-dev bc mercurial wget cpio; make raspberrypi2_wpe_defconfig; make -j3"
