sudo: required

services:
  - docker
  
language: c
  
script:
  - docker pull debian
  - docker run -v $(pwd):/mnt debian /bin/sh -c "cd /mnt; echo 'en_US.UTF-8 UTF-8' > /etc/locale.gen; locale-gen; export LANG=en_US.UTF-8; dpkg-reconfigure locales; apt-get update; apt-get install --assume-yes binutils build-essential git subversion cvs unzip whois ncurses-dev bc mercurial wget cpio; make raspberrypi2_wpe_defconfig; make -j3"
